#!/bin/bash
set -e

echo "SHARD_COUNT=0" > /opt/philbot/shards

bash /usr/bin/philbot_config_populate.sh /var/lib/philbot

iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080
iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-port 4443
bash -c 'iptables-save > /etc/iptables/rules.v4'

bash /usr/bin/philbot_containerized_start.sh
