#!/bin/bash
set -e

rm -f /opt/philbot/env

. /usr/share/debconf/confmodule
db_get philbot-containerized/SHARD_COUNT
echo "SHARD_COUNT=$RET" >> /opt/philbot/env

bash /usr/bin/philbot_config_populate.sh /etc/philbot-containerized

iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080
iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-port 4443
bash -c 'iptables-save > /etc/iptables/rules.v4'

bash /usr/bin/philbot_containerized_start.sh
