#!/bin/bash
if [ -f /usr/bin/philbot_init_otel ]; then
  source /usr/bin/philbot_init_otel
fi
if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
  docker image prune --all --force
fi
rm /var/lib/philbot/collector.yaml /var/lib/philbot/environment.properties.*
rm -r /opt/philbot
exit 0
