#!/bin/bash
if [ -f /usr/bin/philbot_init_otel ]; then
  source /usr/bin/philbot_init_otel
fi
systemctl daemon-reload
if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
  rm -rf /opt/philbot
fi
rm /var/lib/philbot/collector.yaml /var/lib/philbot/environment.properties.*
exit 0
