#!/bin/bash
set -e

bash /usr/bin/philbot_config_populate.sh /etc/philbot-baremetal

wget -O /opt/philbot/libopus.tar.bz2 https://anaconda.org/anaconda/libopus/1.3/download/linux-64/libopus-1.3-h7b6447c_0.tar.bz2
tar -xf /opt/philbot/libopus.tar.bz2 -C /opt/philbot
rm /opt/philbot/libopus.tar.bz2

iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080
iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-port 4443
iptables-save > /etc/iptables/rules.v4

systemctl daemon-reload
systemctl enable philbot_scheduler philbot_discordgateway2http philbot_backend philbot_voice
systemctl start philbot_scheduler philbot_discordgateway2http philbot_backend philbot_voice