#!/bin/bash
sudo systemctl stop philbot-scheduler philbot-discordgateway2http philbot-backend philbot-voice &&
sudo systemctl disable philbot-scheduler philbot-discordgateway2http philbot-backend philbot-voice
