#!/bin/bash
set -e
. /usr/share/debconf/confmodule

db_beginblock
db_input critical philbot/DEPLOYMENT || true
db_endblock

db_beginblock
db_input critical philbot/DISCORD_CLIENT_ID || true
db_endblock

db_go

db_get philbot/DISCORD_CLIENT_ID
db_subst philbot/DISCORD_CLIENT_ID DISCORD_CLIENT_ID $RET

db_beginblock
db_input critical philbot/DISCORD_API_TOKEN || true
db_input critical philbot/OWNER_DISCORD_USER_ID || true
db_endblock

db_beginblock
db_input critical philbot/PUBLIC_URL || true
db_endblock

db_beginblock
db_input critical philbot/SELF_MONITORING || true
db_endblock

db_get philbot/SELF_MONITORING
if [ "$RET" = "yes" ]; then
  root_url="http://philbot.eu"
  db_set philbot/OPENTELEMETRY_TRACES_API_ENDPOINT "$root_url:4318"
  db_set philbot/OPENTELEMETRY_TRACES_API_TOKEN ""
  db_set philbot/OPENTELEMETRY_METRICS_API_ENDPOINT "$root_url:4318"
  db_set philbot/OPENTELEMETRY_METRICS_API_TOKEN ""
  db_set philbot/OPENTELEMETRY_LOGS_API_ENDPOINT "$root_url:4318"
  db_set philbot/OPENTELEMETRY_LOGS_API_TOKEN ""
  db_set philbot/LINK_OBSERVABILITY "$root_url/monitoring"
else
  db_beginblock
  db_input high philbot/OPENTELEMETRY_TRACES_API_ENDPOINT || true
  db_input high philbot/OPENTELEMETRY_TRACES_API_TOKEN || true
  db_input high philbot/OPENTELEMETRY_METRICS_API_ENDPOINT || true
  db_input high philbot/OPENTELEMETRY_METRICS_API_TOKEN || true
  db_input high philbot/OPENTELEMETRY_LOGS_API_ENDPOINT || true
  db_input high philbot/OPENTELEMETRY_LOGS_API_TOKEN || true
  db_input high philbot/LINK_OBSERVABILITY || true
  db_endblock
fi

db_beginblock
db_input high philbot/OPENAI_API_TOKEN || true
db_input high philbot/OPENAI_COST_LIMIT || true
db_input high philbot/GCP_T2S_TOKEN || true
db_input high philbot/GOOGLEAI_COST_LIMIT || true
db_input high philbot/SPEECHIFY_API_TOKEN || true
db_input high philbot/SPEECHIFY_COST_LIMIT || true
db_endblock

db_beginblock
db_input high philbot/YOUTUBE_API_TOKEN || true
db_endblock

db_beginblock
db_input high philbot/RIOT_API_TOKEN || true
db_input high philbot/RIOT_TFT_API_TOKEN || true
db_input high philbot/RAPID_API_TOKEN || true
db_input high philbot/APEX_LEGENDS_API_TOKEN || true
db_input high philbot/TRACKER_GG_API_TOKEN || true
db_endblock

db_go
