source "https://rubygems.org"
gem 'opentelemetry-sdk', '1.5.0'
gem 'opentelemetry-exporter-otlp', '0.29.0'
gem 'opentelemetry-instrumentation-all', '0.67.0'
gem 'opentelemetry-resource_detectors', '0.24.2'
