source "https://rubygems.org"
gem 'opentelemetry-sdk', '1.4.1'
gem 'opentelemetry-exporter-otlp', '0.26.3'
gem 'opentelemetry-instrumentation-all', '0.60.0'
gem 'opentelemetry-resource_detectors', '0.24.2'
