name: Autorelease

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  observe:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/opentelemetry-bash/actions/instrument/workflow@v4.12.3
        env:
          OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/metrics'
          OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/logs'
          OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/traces'
  
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/opentelemetry-bash/actions/instrument/job@v4.12.3
      - uses: plengauer/autorelease@v0.1.0
        with:
          github_token: ${{ secrets.RENOVATE_TOKEN }}
          openai_token: ${{ secrets.OPENAI_API_TOKEN }}
