name: Automatic Version Bump

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  observe:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/opentelemetry-bash/actions/instrument/workflow@v4.32.0
        env:
          OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/metrics'
          OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/logs'
          OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/traces'
          OTEL_SHELL_CONFIG_OBSERVE_SUBPROCESSES: 'TRUE'
          OTEL_SHELL_CONFIG_OBSERVE_SIGNALS: 'TRUE'
  
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/opentelemetry-bash/actions/instrument/job@v4.32.0
      - uses: plengauer/autoversion@v0.16.0
        with:
          github_token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          openai_token: ${{ secrets.OPENAI_API_TOKEN }}
