name: Bump Version Scheduler

on:
  push:
    branches: 'renovate/**'
    paths: 'Scheduler/Gemfile'

jobs:
  observe:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/opentelemetry-bash/actions/instrument/workflow@v4.8.0
        env:
          OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/metrics'
          OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/logs'
          OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/traces'
  
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./Scheduler/
    steps:
      - uses: plengauer/opentelemetry-bash/actions/instrument/job@v4.8.0
      - uses: actions/checkout@v4
      - run: |
          set -e
          version="$(cat philbot-scheduler.gemspec | grep version | cut -d = -f 2 | awk '{ print $1 }' | tr -d "'")"
          major="$(echo "$version" | cut -d . -f 1)"
          minor="$(echo "$version" | cut -d . -f 2)"
          patch="$(echo "$version" | cut -d . -f 3)"
          minor=$((minor + 1))
          patch=0
          sed -i "s/$version/$major.$minor.$patch/g" philbot-scheduler.gemspec
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Version bump
