name: Publish Deployment Configuration

on:
  push:
    branches: main
    paths:
      - 'Deployment/Config/**'
      
jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Deployment/Config

    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install devscripts debhelper
      - run: echo "::set-output name=version::$(cat ./DEBIAN/control | grep 'Version' | awk -F\  '{print $2}')"
        id: version
      - run: dpkg-deb --root-owner-group --build . ../package.deb
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_RELEASE_TOKEN }}
        with:
          tag_name: deployment-config-v${{ steps.version.outputs.version }}
          release_name: Release Deployment Config v${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        id: upload-release-asset 
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Deployment/package.deb
          asset_name: philbot_deployment_config_${{ steps.version.outputs.version }}.deb
          asset_content_type: application/octet-stream
