name: Publish Discord Gateway 2 HTTP Master

on:
  push:
    branches: main
    paths:
      - 'DiscordGateway2HTTPMaster/**'
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: echo "::set-output name=version::$(cat ./DiscordGateway2HTTPMaster/version.txt)"
        id: version
      - uses: docker/build-push-action@v5
        with:
          context: ./DiscordGateway2HTTPMaster/
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/philbot-discordgateway2httpmaster:v${{ steps.version.outputs.version }}, ${{ secrets.DOCKERHUB_USERNAME }}/philbot-discordgateway2httpmaster:latest
          push: true
