name: Publish Debian Configuration

on:
  push:
    branches: main
    paths:
      - 'Deployment/Config/DEBIAN/control'
      
jobs:
  observe:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/opentelemetry-bash/actions/instrument/workflow@v4.7.0
        env:
          OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/metrics'
          OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/logs'
          OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/traces'

  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Deployment/Config

    steps:
      - uses: plengauer/opentelemetry-bash/actions/instrument/job@v4.6.1
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install devscripts debhelper
      - run: echo "::set-output name=version::$(cat ./DEBIAN/control | grep 'Version' | awk -F\  '{print $2}')"
        id: version
      - run: |
          sed -i ./DEBIAN/templates s~__code_url__~https://github.com/$GITHUB_REPOSITORY~g
          sed -i ./DEBIAN/templates s/__parent_domain__/$PARENT_DOMAIN/g
          sed -i ./DEBIAN/config s/__parent_domain__/$PARENT_DOMAIN/g
        env:
          PARENT_DOMAIN: ${{ secrets.PARENT_DOMAIN }}      
      - run: dpkg-deb --root-owner-group -Zgzip --build . ../package.deb
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_RELEASE_TOKEN }}
        with:
          tag_name: deployment-config-v${{ steps.version.outputs.version }}
          release_name: Release Deployment Config v${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Deployment/package.deb
          asset_name: philbot_deployment_config_${{ steps.version.outputs.version }}.deb
          asset_content_type: application/octet-stream
