name: Publish Image Discord Gateway 2 HTTP

on:
  push:
    branches: main
    paths:
      - 'DiscordGateway2HTTP/package.json'

jobs:
  observe:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/opentelemetry-bash/actions/instrument/workflow@v4.32.0
        env:
          OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/metrics'
          OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/logs'
          OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/traces'

  diff:
    runs-on: ubuntu-latest
    outputs:
      dirty: ${{ steps.git-diff.outputs.dirty }}
    steps:
      - uses: plengauer/opentelemetry-bash/actions/instrument/job@v4.32.0
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: git-diff
        run: |
          echo dirty="$(git diff "$GITHUB_SHA"^1 "$GITHUB_SHA" -- DiscordGateway2HTTP/package.json | grep -E "^\+" | grep -q '"version":' && echo true || echo false)" >> "$GITHUB_OUTPUT"

  publish:
    runs-on: ubuntu-latest
    needs: diff
    if: needs.diff.outputs.dirty == 'true'
    steps:
      - uses: plengauer/opentelemetry-bash/actions/instrument/job@v4.32.0
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: echo "version=$(node -p "require('./DiscordGateway2HTTP/package.json').version")" >> "$GITHUB_OUTPUT"
        id: version
      - uses: docker/build-push-action@v6
        with:
          context: ./DiscordGateway2HTTP/
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/philbot-discordgateway2http:v${{ steps.version.outputs.version }}, ${{ secrets.DOCKERHUB_USERNAME }}/philbot-discordgateway2http:latest
          push: true
