name: Publish Collector

on:
  push:
    branches: main
    paths:
      - 'Collector/version.txt'
      - 'Collector/Dockerfile'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/opentelemetry-bash/actions/instrument/job@v4.6.0
        env:
          OTEL_SERVICE_NAME: 'Philbot CI'
          OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: 'http://philbot.eu:4318/v1/metrics'
          OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: 'http://philbot.eu:4318/v1/logs'
          OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: 'http://philbot.eu:4318/v1/traces'
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: echo "::set-output name=version::$(cat ./DiscordGateway2HTTPMaster/version.txt)"
        id: version
      - uses: docker/build-push-action@v5
        with:
          context: ./Collector/
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/philbot-selfmonitoring:v${{ steps.version.outputs.version }}, ${{ secrets.DOCKERHUB_USERNAME }}/philbot-selfmonitoring:latest
          push: true
