name: Publish Scheduler

on:
  push:
    branches: main
    paths:
      - 'Scheduler/**'

jobs:
  publish-gem:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Scheduler/
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.1.x

    - run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      continue-on-error: true
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_TOKEN}}"

  publish-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./Scheduler/
          build-args: APPLICATION_VERSION=unknown
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/philbot-scheduler:latest
          push: true