name: 'Publish Package Voice'

env:
  OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/metrics'
  OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/logs'
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/traces'

on:
  push:
    branches: main
    paths:
      - 'Voice/pyproject.toml'

jobs:
  diff:
    runs-on: ubuntu-latest
    outputs:
      dirty: ${{ steps.git-diff.outputs.dirty }}
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@v5.30.0
        with:
          secrets_to_redact: '["${{ github.token }}"]'
      - uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
      - id: git-diff
        run: |
          echo dirty="$(git diff "$GITHUB_SHA"^1 "$GITHUB_SHA" -- Voice/pyproject.toml | grep -E "^\+" | grep -q 'version' && echo true || echo false)" >> "$GITHUB_OUTPUT"
    permissions:
      actions: read
  publish:
    runs-on: ubuntu-latest
    needs: diff
    if: needs.diff.outputs.dirty == 'true'
    defaults:
      run:
        working-directory: ./Voice/
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@v5.30.0
        with:
          secrets_to_redact: '["${{ github.token }}","${{secrets.PYPI_TOKEN}}"]'
      - uses: actions/checkout@v5.0.0
      - uses: actions/setup-python@v6.0.0
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip
          pip install twine
          pip install build
      - run: python -m build
      - run: twine upload --username __token__ ./dist/*
        env:
          TWINE_PASSWORD: ${{secrets.PYPI_TOKEN}}
    permissions:
      actions: read
