name: Publish Debian Configuration

on:
  push:
    branches: main
    paths:
      - 'Deployment/Config/DEBIAN/control'
      
jobs:
  observe:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/opentelemetry-bash/actions/instrument/workflow@v4.30.0
        env:
          OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/metrics'
          OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/logs'
          OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/traces'

  diff:
    runs-on: ubuntu-latest
    outputs:
      dirty: ${{ steps.git-diff.outputs.dirty }}
    steps:
      - uses: plengauer/opentelemetry-bash/actions/instrument/job@v4.30.0
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: git-diff
        run: |
          echo dirty="$(git diff "$GITHUB_SHA"^1 "$GITHUB_SHA" -- Deployment/Config/DEBIAN/control | grep -E "^\+" | grep -q 'Version: ' && echo true || echo false)" >> "$GITHUB_OUTPUT"

  publish:
    runs-on: ubuntu-latest
    needs: diff
    if: needs.diff.outputs.dirty == 'true'
    defaults:
      run:
        working-directory: ./Deployment/Config

    steps:
      - uses: plengauer/opentelemetry-bash/actions/instrument/job@v4.30.0
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install devscripts debhelper
      - run: echo "version=$(cat ./DEBIAN/control | grep 'Version' | awk -F\  '{print $2}')" >> "$GITHUB_OUTPUT"
        id: version
      - run: |
          sed -i "s~__code_url__~https://github.com/$GITHUB_REPOSITORY~g" ./DEBIAN/templates
          sed -i "s/__parent_domain__/$PARENT_DOMAIN/g" ./DEBIAN/templates
          sed -i "s/__parent_domain__/$PARENT_DOMAIN/g" ./DEBIAN/config
        env:
          PARENT_DOMAIN: ${{ secrets.PARENT_DOMAIN }}      
      - run: dpkg-deb --root-owner-group -Zgzip --build . ../package.deb
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
        with:
          tag_name: deployment-config-v${{ steps.version.outputs.version }}
          release_name: Release Deployment Config v${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Deployment/package.deb
          asset_name: philbot_deployment_config_${{ steps.version.outputs.version }}.deb
          asset_content_type: application/octet-stream
