name: Publish Image Discord Gateway 2 HTTP

on:
  push:
    branches: main
    paths:
      - 'DiscordGateway2HTTP/package.json'
      - 'DiscordGateway2HTTP/Dockerfile'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: echo "::set-output name=version::$(node -p "require('./DiscordGateway2HTTP/package.json').version")"
        id: version
      - uses: docker/build-push-action@v5
        with:
          context: ./DiscordGateway2HTTP/
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/philbot-discordgateway2http:v${{ steps.version.outputs.version }}, ${{ secrets.DOCKERHUB_USERNAME }}/philbot-discordgateway2http:latest
          push: true
