name: Publish Image Voice

on:
  push:
    branches: main
    paths:
      - 'Voice/pyproject.toml'
      - 'Voice/Dockerfile'

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: echo "::set-output name=version::$(cat ./Voice/pyproject.toml | grep version | grep -E '[0-9]+\.[0-9]+\.[0-9]+' -o)"
        id: version
      - uses: docker/build-push-action@v5
        with:
          context: ./Voice/
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/philbot-voice:v${{ steps.version.outputs.version }}, ${{ secrets.DOCKERHUB_USERNAME }}/philbot-voice:latest
          push: true
