name: 'Publish Image Voice'

env:
  OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/metrics'
  OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/logs'
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/traces'

on:
  push:
    branches: main
    paths:
      - 'Voice/pyproject.toml'

permissions:
  contents: read
  actions: read
jobs:
  diff:
    runs-on: ubuntu-latest
    outputs:
      dirty: ${{ steps.git-diff.outputs.dirty }}
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@v5.27.0
        with:
          secrets_to_redact: '["${{ github.token }}"]'
      - uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
      - id: git-diff
        run: |
          echo dirty="$(git diff "$GITHUB_SHA"^1 "$GITHUB_SHA" -- Voice/pyproject.toml | grep -E "^\+" | grep -q 'version' && echo true || echo false)" >> "$GITHUB_OUTPUT"
    permissions:
      actions: read
  publish:
    runs-on: ubuntu-latest
    needs: diff
    if: needs.diff.outputs.dirty == 'true'
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@v5.27.0
        with:
          secrets_to_redact: '["${{ github.token }}","${{ secrets.DOCKERHUB_TOKEN }}","${{ secrets.DOCKERHUB_USERNAME }}"]'
      - uses: actions/checkout@v5.0.0
      - uses: docker/setup-qemu-action@v3.6.0
      - uses: docker/setup-buildx-action@v3.11.1
      - uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: echo "version=$(cat ./Voice/pyproject.toml | grep version | grep -E '[0-9]+\.[0-9]+\.[0-9]+' -o)" >> "$GITHUB_OUTPUT"
        id: version
      - uses: docker/build-push-action@v6.18.0
        with:
          context: ./Voice/
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/philbot-voice:v${{ steps.version.outputs.version }}, ${{ secrets.DOCKERHUB_USERNAME }}/philbot-voice:latest
          push: true
    permissions:
      actions: read
