name: 'Publish Image Scheduler'

env:
  OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/metrics'
  OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/logs'
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/traces'

on:
  push:
    branches: main
    paths:
      - 'Scheduler/philbot-scheduler.gemspec'

jobs:
  diff:
    runs-on: ubuntu-latest
    outputs:
      dirty: ${{ steps.git-diff.outputs.dirty }}
    steps:
      - uses: plengauer/opentelemetry-bash/actions/instrument/job@v5.19.2
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - id: git-diff
        run: |
          echo dirty="$(git diff "$GITHUB_SHA"^1 "$GITHUB_SHA" -- Scheduler/philbot-scheduler.gemspec | grep -E "^\+" | grep -q '.version' && echo true || echo false)" >> "$GITHUB_OUTPUT"

  publish:
    runs-on: ubuntu-latest
    needs: diff
    if: needs.diff.outputs.dirty == 'true'
    steps:
      - uses: plengauer/opentelemetry-bash/actions/instrument/job@v5.19.2
      - uses: actions/checkout@v4.2.2
      - uses: docker/setup-qemu-action@v3.6.0
      - uses: docker/setup-buildx-action@v3.10.0
      - uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: echo "version=$(cat ./Scheduler/philbot-scheduler.gemspec | grep 'version' | awk -F\' '{print $2}')" >> "$GITHUB_OUTPUT"
        id: version
      - uses: docker/build-push-action@v6.18.0
        with:
          context: ./Scheduler/
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/philbot-scheduler:v${{ steps.version.outputs.version }}, ${{ secrets.DOCKERHUB_USERNAME }}/philbot-scheduler:latest
          push: true
