name: Publish ShardsMaster

on:
  push:
    branches: main
    paths:
      - 'ShardsMaster/**'
  schedule:
    - cron: "0 0 1 * *"

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: echo "::set-output name=version::$(cat ./ShardsMaster/VERSION)"
        id: version
      - uses: docker/build-push-action@v4
        with:
          context: ./ShardsMaster/
          build-args: APPLICATION_VERSION=${{ steps.version.outputs.version }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/philbot-shards-master:v${{ steps.version.outputs.version }}, ${{ secrets.DOCKERHUB_USERNAME }}/philbot-shards-master:latest
          push: true
