name: Publish Image Voice

on:
  push:
    branches: main
    paths:
      - 'Voice/pyproject.toml'
      - 'Voice/Dockerfile'

permissions:
  contents: read

jobs:
  observe:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/opentelemetry-bash/actions/instrument/workflow@v4.12.2
        env:
          OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/metrics'
          OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/logs'
          OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/traces'

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/opentelemetry-bash/actions/instrument/job@v4.12.2
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: echo "version=$(cat ./Voice/pyproject.toml | grep version | grep -E '[0-9]+\.[0-9]+\.[0-9]+' -o)" >> "$GITHUB_OUTPUT"
        id: version
      - uses: docker/build-push-action@v5
        with:
          context: ./Voice/
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/philbot-voice:v${{ steps.version.outputs.version }}, ${{ secrets.DOCKERHUB_USERNAME }}/philbot-voice:latest
          push: true
