name: Publish Collector

on:
  push:
    branches: main
    paths:
      - 'Collector/version.txt'
      - 'Collector/Dockerfile'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: echo "::set-output name=version::$(cat ./DiscordGateway2HTTPMaster/version.txt)"
        id: version
      - uses: docker/build-push-action@v5
        with:
          context: ./Collector/
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/philbot-selfmonitoring:v${{ steps.version.outputs.version }}, ${{ secrets.DOCKERHUB_USERNAME }}/philbot-selfmonitoring:latest
          push: true
