name: Publish Voice

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Voice/
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      run: twine upload --username philipplengauer ./dist/*
        continue-on-error: true
        env:
          TWINE_PASSWORD: ${{secrets.PYPI_PASSWORD}}
      # uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      # continue-on-error: true
      # with:
      #  user: philipplengauer
      #  password: ${{ secrets.PYPI_TOKEN }}
