name: Publish Scheduler

on:
  push:
    branches: main
    paths:
      - 'Scheduler/**'
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  publish-gem:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Scheduler/
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.1.x

    - run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      continue-on-error: true
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_TOKEN}}"

  publish-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: echo "::set-output name=version::$(cat ./Scheduler/philbot-scheduler.gemspec | grep 'version' | awk -F\' '{print $2}')"
        id: version
      - uses: docker/build-push-action@v5
        with:
          context: ./Scheduler/
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/philbot-scheduler:v${{ steps.version.outputs.version }}, ${{ secrets.DOCKERHUB_USERNAME }}/philbot-scheduler:latest
          push: true