name: Test Smoke

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
      
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: "Prepare system"
        run: |
          sudo apt-get update
          sudo apt-get -y dist-upgrade
          sudo apt-get -y remove containerd.io
      - name: "Install bot"
        env:
          PHILBOT_APPLICATION_ID: ${{ secrets.PHILBOT_APPLICATION_ID }}
          PHILBOT_API_TOKEN: ${{ secrets.PHILBOT_API_TOKEN }}
          PHILBOT_YOUTUBE_TOKEN: ${{ secrets.PHILBOT_YOUTUBE_TOKEN }}
          PHILBOT_OPENAI_TOKEN: ${{ secrets.PHILBOT_OPENAI_TOKEN }}
        run: |
          sudo apt-get install -y debconf-utils
          {
            echo philbot-config philbot/DEPLOYMENT select staging
            echo philbot-config philbot/DISCORD_CLIENT_ID string $PHILBOT_APPLICATION_ID
            echo philbot-config philbot/DISCORD_API_TOKEN string $PHILBOT_API_TOKEN
            echo philbot-config philbot/SELF_MONITORING select yes
            echo philbot-config philbot/OWNER_DISCORD_USER_ID string 305778551167254529
            echo philbot-config philbot/YOUTUBE_API_TOKEN string $PHILBOT_YOUTUBE_TOKEN
            echo philbot-config philbot/OPENAI_API_TOKEN string $PHILBOT_OPENAI_TOKEN
            echo philbot-config philbot/OPENAI_COST_LIMIT string 1
          } | sudo debconf-set-selections
          wget -O - https://raw.githubusercontent.com/plengauer/philbot/main/INSTALL.sh | sh -E
      - name: "Test Webserver"
        run: wget http://127.0.0.1/
      - name: "Test AI"
        env:
          PHILBOT_APPLICATION_ID: ${{ secrets.PHILBOT_APPLICATION_ID }}
          PHILBOT_API_TOKEN: ${{ secrets.PHILBOT_API_TOKEN }}
        run: |
          channel_id='1149981968549806101'
          message_id="$(curl -H "authorization: Bot $PHILBOT_API_TOKEN" -H 'content-type: application/json' -d "{\"content\": \"<@$PHILBOT_APPLICATION_ID> hello, how are you?\"}" https://discord.com/api/v10/channels/$channel_id/messages)"
          while ! curl --fail -H "authorization: Bot $PHILBOT_API_TOKEN" https://discord.com/api/v10/channels/$channel_id/messages | jq -r .[].referenced_message.id | grep -F "$message_id"; do
            sleep 10
          done
      - name: "Test Voice"
        env:
          PHILBOT_APPLICATION_ID: ${{ secrets.PHILBOT_APPLICATION_ID }}
          PHILBOT_API_TOKEN: ${{ secrets.PHILBOT_API_TOKEN }}
        run: |
          guild_id='977181350509555752' # TODO can we make these dynamic? or secrets?
          channel_id='1149981968549806101'
          channel_name='staging'
          # TODO manually activate player!
          message_id="$(curl -H "authorization: Bot $PHILBOT_API_TOKEN" -H 'content-type: application/json' -d "{\"content\": \"<@$PHILBOT_APPLICATION_ID> play in $channel_name Rick Astley Never Gonna Give You Up\"}" https://discord.com/api/v10/channels/$channel_id/messages)"
          while ! ls /var/lib/memory/philbot/player_voice_channel_guild_"$guild_id".json; do; sleep 1; do
          while ! ls /var/lib/memory/philbot/voice_channel_user_"$PHILBOT_APPLICATION_ID".json; do; sleep 1; do
          sleep 60
          while ! ls /var/lib/memory/philbot/voice_channel_user_"$PHILBOT_APPLICATION_ID".json; do; sleep 1; do
          while ls /var/lib/memory/philbot/voice_channel_user_"$PHILBOT_APPLICATION_ID".json; do; sleep 1; do
      - name: "Cleanup"
        run: |
          sudo apt-get -y remove philbot
          sudo apt-get -y auto-remove
          sudo apt-get -y auto-clean
