name: Update Package Repository

on:
  release:
    types: published
  push:
    branches:
      - main
    paths:
      - .github/workflows/update_package_repository.yml

concurrency:
  group: update-package-repository
      
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      actions: read
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@v5.47.3
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: '["${{ github.token }}"]'
      - uses: plengauer/create-package-repository@v0.2.0
      - uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: .
      - uses: actions/deploy-pages@v4.0.5
