name: Publish Voice

on:
  push:
    branches: main
    paths:
      - 'Voice/pyproject.toml'

permissions:
  contents: read

jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Voice/
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - run: |
        python -m pip install --upgrade pip
        pip install twine
        pip install build
    - run: python -m build
    - run: twine upload --username philipplengauer ./dist/*
      env:
        TWINE_PASSWORD: ${{secrets.PYPI_PASSWORD}}

  publish-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: echo "::set-output name=version::$(cat ./Voice/pyproject.toml | grep version | grep -E '[0-9]+\.[0-9]+\.[0-9]+' -o)"
        id: version
      - uses: docker/build-push-action@v5
        with:
          context: ./Voice/
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/philbot-voice:v${{ steps.version.outputs.version }}, ${{ secrets.DOCKERHUB_USERNAME }}/philbot-voice:latest
          push: true
